version: '3.8'

services:
  equipment-tracker:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./Resources:/app/Resources
      - ./output:/app/output
      - ./app/data:/app/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - DATA_DIR=Resources
      - JSON_DATA_DIR=app/data
      - MAIL_SERVER=smtp.marybird.com
      - MAIL_PORT=587
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_USE_TLS=True
      - MAIL_DEFAULT_SENDER=equipment-tracker@marybird.com
      # Set this to your machine's network IP for external access (e.g., 192.168.1.11)
      - APPLICATION_URL=${APPLICATION_URL:-http://localhost:5000}
  
  cron:
    build:
      context: .
      dockerfile: cron_jobs/Dockerfile.cron
    volumes:
      - ./app/data:/app/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATA_DIR=Resources
      - JSON_DATA_DIR=app/data
      - MAIL_SERVER=smtp.marybird.com
      - MAIL_PORT=587
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_USE_TLS=True
      - MAIL_DEFAULT_SENDER=equipment-tracker@marybird.com
      - APPLICATION_URL=http://localhost:5000